# Generated by Django 5.0.3 on 2024-05-01 14:51

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_custuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('custuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('accounts.custuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='custuser',
            name='role',
            field=models.CharField(choices=[('WardMember', 'WardMember'), ('Users', 'Users'), ('Authority', 'Authority')], default='Users', max_length=100),
        ),
    ]
