# Generated by Django 5.0.3 on 2024-04-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_alter_custuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='aadhar',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='local_body',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='ward',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
