# Generated by Django 5.0.3 on 2024-04-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_users_aadhar_alter_users_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_body', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_solved', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
