# Generated by Django 5.0.3 on 2024-05-01 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authority_alter_custuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingRecom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_member', models.BooleanField(default=False)),
                ('is_authority', models.BooleanField(default=False)),
                ('solved', models.BooleanField(default=False)),
                ('recom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.complaint')),
            ],
        ),
    ]
