# Generated by Django 5.0.3 on 2024-04-03 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='local_body',
            new_name='localbody',
        ),
    ]
