# Generated by Django 5.0.3 on 2024-05-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_trackingrecom'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='authority',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Not Available', 'Not Available')], default='Not Available', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='member',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Not Available', 'Not Available')], default='Not Available', max_length=100, null=True),
        ),
    ]
