# Generated by Django 5.0.3 on 2024-04-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_local_body_complaint_localbody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
